# Generated by Django 4.2.1 on 2023-05-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tables",
            name="image",
        ),
        migrations.RemoveField(
            model_name="tables",
            name="layout",
        ),
    ]
